name: Demo workflow
on: workflow_dispatch
jobs:
    print: 
      runs-on: ubuntu-latest
      steps:
        - name: Print to console
          run: echo "Hello Git Actions"
        - name: Print lines
          run: |
            echo "Git line #1"
            echo "Git line #2"
